=== vigeomart/ZVPGTZWebXML/ZVPGTZ_0930/ZPVGTZ_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ZVPGTZ_kurzusfelvetel (hallgato,kurzusok)>
<!ELEMENT hallgato (hnev,szulev,szak)>
<!ELEMENT kurzusok (kurzus*)>
<!ELEMENT kurzus (kurzusnev,kredit,hely,idopont+,(oktato|oraado))>

<!ATTLIST ZVPGTZ_kurzusfelvetel tanev CDATA #REQUIRED>
<!ATTLIST ZVPGTZ_kurzusfelvetel egyetem CDATA #REQUIRED>

<!ATTLIST szak evf CDATA #REQUIRED>

<!ATTLIST kurzus id ID #REQUIRED>
<!ATTLIST kurzus jovahagyas (igen | nem) "nem">
<!ATTLIST kurzus nyelv (német | angol | magyar) "magyar">

<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>

<!ELEMENT oraado (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>

=== vigeomart/ZVPGTZWebXML/ZVPGTZ_0930/ZVPGTZ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ZVPGTZ_kurzusfelvetel SYSTEM "../ZVPGTZ_0930/ZPVGTZ_kurzusfelvetel.dtd">

<ZVPGTZ_kurzusfelvetel tanev="2026" egyetem="ME">
    <hallgato>
        <hnev>Veres Martin</hnev>
        <szulev>2006</szulev>
        <szak evf="3">Programtervező informatikus</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="GEIAL331-B2-00">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>V.előadó</hely>
            <idopont>10:00</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAL331-B2-01" jovahagyas = "igen" nyelv="magyar">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>In/101</hely>
            <idopont>14:00</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B2-00" jovahagyas = "nem" nyelv="angol">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.előadó</hely>
            <idopont>10:00</idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B2-01">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXIII.előadó</hely>
            <idopont>8:00</idopont>
            <oraado></oraado>
        </kurzus>
        <kurzus id="GEMAK234-B2-00">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX.előadó</hely>
            <idopont>14:00</idopont>
            <oktato>Dr. Házy Attila</oktato>
        </kurzus>
        <kurzus id="GEMAK234-B2-01">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX.előadó</hely>
            <idopont>16:00</idopont>
            <oktato>Dr. Házy Attila</oktato>
        </kurzus>
        <kurzus id="GEIAL32K-B2-00" jovahagyas = "igen" nyelv="német">
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>In/202</hely>
            <idopont>8:00</idopont>
            <oraado></oraado>
        </kurzus>
        <kurzus id="GEIAL32K-B2-01">
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>In/101</hely>
            <idopont>8:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAL315-B2-00">
            <kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
            <kredit>5</kredit>
            <hely>In/103</hely>
            <idopont>14:00</idopont>
            <oktato>Dr. Sasvári Péter László</oktato>
        </kurzus>
        <kurzus id="GEIAL315-B2-01">
            <kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
            <kredit>5</kredit>
            <hely>In/103</hely>
            <idopont>18:00</idopont>
            <oktato>Dr. Sasvári Péter László</oktato>
        </kurzus>
    </kurzusok>    
</ZVPGTZ_kurzusfelvetel>
