=== vigeomart/ZVPGTZWebXML/ZVPGTZ_0930/ZVPGTZ_orarend.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT orarend (ora+)>
<!ELEMENT ora (targy, ido, helyszin, oktato, szak)>
<!ELEMENT ido (nap,tol,ig)>

<!ATTLIST ora id ID #REQUIRED>
<!ATTLIST ora tipus CDATA #IMPLIED >

<!ELEMENT targy (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>

<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>

=== vigeomart/ZVPGTZWebXML/ZVPGTZ_0916/ZVPGTZ_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE orarend SYSTEM "../ZVPGTZ_0930/ZVPGTZ_orarend.dtd">

<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../ZVPGTZ_1007/ZVPGTZ_orarend.xsd">
    <ora id="GEIAL331-B2-00" tipus="eloadas">
        <targy>Web technológiák 1.</targy>
        <ido>
            <nap>Hétfő</nap>
            <tol>10</tol>
            <ig>12</ig>
        </ido>
        <helyszin>V.előadó</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAL331-B2-01" tipus="gyakorlat">
        <targy>Web technológiák 1.</targy>
        <ido>
            <nap>Hétfő</nap>
            <tol>14</tol>
            <ig>16</ig>
        </ido>
        <helyszin>In/101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAK130-B2-00" tipus="eloadas">
        <targy>Mesterséges intelligencia alapok</targy>
        <ido>
            <nap>Kedd</nap>
            <tol>10</tol>
            <ig>12</ig>
        </ido>
        <helyszin>XXXII.előadó</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    
    <ora id="GEIAK130-B2-01" tipus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <ido>
            <nap>Kedd</nap>
            <tol>8</tol>
            <ig>10</ig>
        </ido>
        <helyszin>XXXII.előadó</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEMAK234-B2-00" tipus="eloadas">
        <targy>Algoritmusok és vizsgálatuk</targy>
        <ido>
            <nap>Kedd</nap>
            <tol>14</tol>
            <ig>16</ig>
        </ido>
        <helyszin>XXX.előadó</helyszin>
        <oktato>Dr. Házy Attila</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEMAK234-B2-01" tipus="gyakorlat">
        <targy>Algoritmusok és vizsgálatuk</targy>
        <ido>
            <nap>Kedd</nap>
            <tol>16</tol>
            <ig>18</ig>
        </ido>
        <helyszin>XXX.előadó</helyszin>
        <oktato>Dr. Házy Attila</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAL32K-B2-00" tipus="eloadas">
        <targy>Webes adatkezelő környezetek</targy>
        <ido>
            <nap>Szerda</nap>
            <tol>8</tol>
            <ig>10</ig>
        </ido>
        <helyszin>In/202</helyszin>
        <oktato>Dr. Kovács László József</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAL32K-B2-01" tipus="gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <ido>
            <nap>Szerda</nap>
            <tol>12</tol>
            <ig>14</ig>
        </ido>
        <helyszin>In/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAL315-B2-00" tipus="eloadas">
        <targy>Vállalati információs rendszerek fejlesztése</targy>
        <ido>
            <nap>Szerda</nap>
            <tol>14</tol>
            <ig>16</ig>
        </ido>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>

    <ora id="GEIAL315-B2-01" tipus="gyakorlat">
        <targy>Vállalati információs rendszerek fejlesztése</targy>
        <ido>
            <nap>Szerda</nap>
            <tol>18</tol>
            <ig>20</ig>
        </ido>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
</orarend>
